### ISSUE TITLE
A calendar for BTV streaming schedule

### ISSUE THREAD

**Issue by EndenDragon** [BronyTV/bronytv.net#33]
I've been with BTV for bout a month or so, yet I still do not know what the programming for the streams are (some say i live under the rock). So I am going to implement a calendar which ties with the google calendar API and add a page on BTV for a custom responsive calendar. I will start when I have a lot of free time (weekend maybe?).

**Comment by uecasm** [comment]
We used to have a simple static page, which people would forget to update.
Then we had (but never put on the site) a google calendar, which people would forget to update.
Then I asked people if they wanted the static page back until we put the calendar on the site (or found something else that we'd forget to update), but people forgot to answer.
