### ISSUE TITLE
Where's rariboard?

### ISSUE THREAD

**Issue by Cuddley** [BronyTV/bronytv.net#4]
Rariboard is love, rariboard is life.

**Comment by AppleDash** [comment]
Soon (tm)

**Comment by omnicons** [comment]
Just to point it out here rariboard isn't gonna be a thing on mobile, at least not in the old itteration of rariboard.

**Comment by Cuddley** [comment]
I'd expect it not to be. It was only implemented to get news across to people who disabled chat.

**Comment by EndenDragon** [comment]
Implemented @ #14
